# SonarQube/SonarCloud properties
# Ambiente do projeto: Python 3.13.9
sonar.python.version=3.13

# SonarQube Cloud
sonar.host.url=https://sonarcloud.io
sonar.organization=micaelrosario
sonar.projectKey=micaelrosario_engenharia2

# Escopo de análise
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Cobertura (gerada no CI/local via: python -m coverage xml)
sonar.python.coverage.reportPaths=coverage.xml